# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Howard's ups and downs
author: Howard Cheung
email: howard.at@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting Howard's ups and downs in his engineering research in thermal
  systems, his work on engineering energy-saving building applications, his
  thought processes, and his boring daily routines
baseurl: "" # the subpath of your site, e.g. /blog
url: "howardcheung.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: howardat
github_username: howardcheung

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-slate
# repository: pages-themes/slate
plugins_dir:
  - jekyll-feed
keep_files: 
  - publications/2014 IEA HP - DHP Fault Modeling Paper.pdf
  - publications/Final_dissertation_edit.pdf
disqus:
  shortname: https-howardcheung-github-io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
